### ISSUE TITLE
retrieveParametersFromServer Paramter

### ISSUE THREAD

**Issue by timtrinidad** [onelogin/php-saml#130]
The retrieveParametersFromServer parameter was added for ADFS compatibility in #37. It looks like that setting conforms better to the document referenced in https://github.com/onelogin/php-saml/pull/37/commits/ce3bf78afb9ffa5733c2263a5c1831413d7dd521. 

At this point, is there any reason not to leave retrieveParametersFromServer TRUE for all setups, including non-ADFS ones?

**Comment by pitbulk** [comment]
Some php-saml running under Nginx can experience issues with QUERY_STRING

**Comment by timtrinidad** [comment]
Interesting - we're currently using nginx. Can you provide more details on what issues we might experience?

Our initial tests on nginx/php-fpm show that leaving the parameter to TRUE works for logout requests from both ADFS and SimpleSamlPHP.

**Comment by pitbulk** [comment]
I don't remember who reported that. I will review Issues/mails.

**Comment by xhienne** [comment]
For the record, I have been bitten by this while using BIG-IP APM's SAML2 module. Because SAML2 LogoutRequests and LogoutResponses were URL-encoded with lower-case hexadecimal numbers, the signature validation kept failing. Problem was solved by setting `retrieveParametersFromServer` to TRUE.

I don't get why this is not the default. If parameters are URL-encoded with lowercases, this is very very unlikely that the signature would have been computed with the uppercase version.
