### ISSUE TITLE
Signing key rollover in Azure

### ISSUE THREAD

**Issue by thompsa** [onelogin/php-saml#140]
On the 15th Microsoft will be rolling over the signing key for AAD SAML/WS-Fed. I can see that they have both keys in the current metadata but reading through this library I dont believe automatic rollover is supported. This isnt really a bug but i thought I would raise it here for comment. I am not falimiar with the standard to know if this should be supported or if it is just a quirk of theirs.

**Comment by pitbulk** [comment]
Roll over is not supoorted, but you can chsnge the cert dinamically as I already suggested on the ruby-saml toolkit: https://github.com/onelogin/ruby-saml/issues/266#issuecomment-215268465

Maybe we support this feature in the future.

**Comment by madmatt** [comment]
Hey @pitbulk, I'm also starting to take a quick look at something like this.

At a glance, it looks like the only thing required is to support either a string or an array of strings for the `$settings['idp']['x509cert']`, and leave it up to the implementing application to provide the correct certificates (and store them locally, or look them up from Azure's FederationMetadata.xml every time, or whatever they want to do).

This would necessitate some changes throughout the response processing, but it looks like they wouldn't be too minor, and could be pulled into different methods to keep the codebase relatively clean.

Would this change be something acceptable for the onelogin/php-saml module, or is it unlikely to be supported because you'd then need to port and maintain it for all other language variants of your module?

Cheers,
Matt.

**Comment by pitbulk** [comment]
Support an array on the $settings['idp']['x509cert'] attribute can allow the dev to not only add a temp cert (required during the rollover), but be able to add several certs.

I think is better if we provide an alternative cert:  $settings['idp']['x509certAlternative']
And on since validation we check with that cert if the normal validation process fail.

This will cover IdP rollover, but we need to also take care of SP rollover

**Comment by madmatt** [comment]
The Azure AD docs aren't particularly clear on just how many signing keys they might advertise at any time. I've kept an eye on the file for a few weeks now, and I've only ever seen two, but I can imagine a situation where they might advertise three (think of a private key disclosure while they're rolling out a new standby certificate for example).

Anyway, I've asked the question to them in a couple of places and will wait to see what they say. Either solution works for me.

**Comment by richard-smith-preservica** [comment]
Hi all,

I've had a similar problem with our Azure AD IDP, which is giving me 3 signing certificates, and it changed which one it was using to sign a request, resulting in this library not authenticating when it did yesterday.

I've made a local change to do what @madmatt suggested - allowing the x509cert in the settings to be an array, and adding all of the certificates returned in the metadata document to that in our application code. At least for SSO requests (which is what we're using it for), it doesn't have a big impact and it does work.

I'm not sure whether Azure is giving us 3 certs because of rollover or just because it wants to rotate them (none are nearing expiry). There is no distinction between the 3 certs in the metadata file that I can see.

I can tidy this up into a pull request if that would be useful.

**Comment by pitbulk** [comment]
Yes please, share your PR, it will help people looking for that functionality and I will review it and see how finally we fix that.

**Comment by richard-smith-preservica** [comment]
I've created a pull request for this change. I haven't updated the tests because I'm not sure how to run them but hopefully it is fairly easy to add a test case for multiple sig certs.

**Comment by pitbulk** [comment]
@thompsa , @madmatt, @richard-smith-preservica   I finally implemented it on [206](https://github.com/onelogin/php-saml/pull/206), please take a look and let me know if works for you.

**Comment by thompsa** [comment]
I have updated our application to v2.10.6 and the x509certMulti feature is working well, thanks.
