### ISSUE TITLE
Settings getValues method doesn't exist

### ISSUE THREAD

**Issue by jeffturcotte** [onelogin/php-saml#176]
https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Settings.php#L127

The getValues method on this line doesn't exist, which means that you can't supply a Settings object to a Settings object. I ran into this issue when trying to use a Settings object as the first argument to the Auth constructor:

```
$settingsObject = new OneLogin_Saml2_Settings($settingsArray);
$auth = new OneLogin_Saml2_Auth($settingsObject);
```

Thanks.

**Comment by pitbulk** [comment]
In order to maintain compatibility with the old version of the toolkit ([Saml library), we support
[OneLogin_Saml_Settings](https://github.com/onelogin/php-saml/blob/master/lib/Saml/Settings.php#L8) objects which has the [getValues](https://github.com/onelogin/php-saml/blob/master/lib/Saml/Settings.php#L57) method, to be provided to the Auth constructor. But you are not able to provide a OneLogin_Saml2_Settings object.

In order to initialize the auth or the  class OneLogin_Saml2_Settings you can provide nothing (the settings file will be read), an array or an OneLogin_Saml_Settings object, not a OneLogin_Saml2_Settings object.

More related info: https://github.com/onelogin/php-saml#settings

**Comment by jeffturcotte** [comment]
Thanks @pitbulk
