### ISSUE TITLE
How to refresh SSO session without doing again ACS

### ISSUE THREAD

**Issue by dieg87** [onelogin/php-saml#187]
Hi,
I'm hoping that someone can bring me a little help.... I'm using this package with aacotroneo for Laravel 5.3. I can do both operation (login, logout) but I have a problem. SSO session expires in 15 minutes and the problem that I have is that I'm doing ACS (for login) and then only using my app (so for SSO that session is idle the all time). I wanna know if there is a method or something to pop up in order to keep alive SSO session, because when SSO session expired I can't logout from IDP because that session doesn't exists anymore.

Thank you for developing this package!

**Comment by pitbulk** [comment]
Your alternatives:
- Sync the value of IdP and SP session timelife.
- Force IdP logout when SP session expires.

Otherwise, I don't see your current behavior that bad, when SP session expires, you wil be redirected to the IdP and since there is an active session there, a SAMLResponse will be sent to the ACS endpoint and your user will be again logged in.

A more complex solution is to implement a back-channel method, able to interact with the IdP to retrieve session info and prolong the lifetime of the SP session

If you google about SAML Single Logout and timelife sessions you will find multiple entries with different approaches and points of views.

**Comment by dieg87** [comment]
Hi Pitbluk,
Thanks for your response. Is more complex the behavior, because when I logged in, the session of SSO is going to be idle the all time, but the session of my app is not going to be idle because I'm interacting with it. So doing a sync between both values is not going to work. For example I'm working in my app for 20 minutes (actively) then I decided to logout, so I'm going to report to the IDP that the session index #xxxx has finished, but the IDP is going to tell me that the session I'm sending to him is not longer valid (because is valid only for 15 minutes), so is not going to redirect me to my app in order to kill my local session.

Is there any solution to fix this? 

Thanks!

**Comment by pitbulk** [comment]
I don't have a solution, but here are some interesting links:
- https://danieleads.com/the-everyday-guide-to-saml-timeouts/
- http://soasecurity.org/2013/06/28/how-saml2-single-logout-works/
- https://wiki.mozilla.org/Security/Guidelines/SAML#Session_handling
- https://hal.inria.fr/hal-01470498/document
