### ISSUE TITLE
Allow "optional" mode for Assertion Encryption - Include "encryption" Certificate in SP Metadata

### ISSUE THREAD

**Issue by timtrinidad** [onelogin/php-saml#268]
We recently upgrades from 2.7.0 to 2.11.0. We have the defaults of:
```
wantNameIdEncrypted: false
wantAssertionsEncrypted: false
```

In 2.7.0, these would send the encryption certificate in the SP metadata but not require encryption for the NameID or Assertion; however, I think that they allowed the IdP to encrypt it (optional encryption). 

This is something we were using as a number of our IdPs may or may not encrypt at their own discretion - upgrading caused those who encrypt to break, and changing `wantAssertionsEncrypted` to `true` would cause those who don't encrypt to break.

After #102/#118, there are now two modes:
* Require encryption (i.e. encryption cert is sent in SP metadata and is required on assertion)
* Require unencrypted (i.e. encryption cert is not sent in SP metadata and is not required on assertion)

There is a third mode that we would like to see that reflected what was happening in 2.7.0:
* Optional encryption (i.e. encryption cert is sent in SP metadata but is not required on assertion).

This may possibly be accomplished by setting `wantAssertionsEncrypted` and `wantNameIdEncrypted` to `null` rather than `true/false`. Let me know what you think about the approach and I can put together a PR.

**Comment by pitbulk** [comment]
Hi @timtrinidad.

Some IdPs by default encrypt the Assertion automatically if the SP metadata that they register contain a KeyDescriptor with  use="encryption".

We decided to only publish KeyDescriptor with use="encryption" if 'wantNameIdEncrypted' or 'wantAssertionsEncrypted' are enabled.

If an IdP want to encrypt, it requires SP public certificate, so will need to ask SP admin to provide it, in this case, by adding private & public certificate in the SAML settings and enabling 'wantAssertionsEncrypted' so that info will be available on metadata file. That is the expected flow that we want.

```
upgrading caused those who encrypt to break, 
```
If they encrypt, means that they already had a SP public certificate registered so they should be able to do that, if they update metadata automatically and they lost that SP public certificate for encrypt, then I don't think it will break and simply IdPs will not encrypt.


If you want a different behavior, rather than adding new settings or changing the logic of current values, we can modify the [getSPMetadata](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Settings.php#L807) method and add a $wantsEncrypted, so you will be able to use it and SP metadata always will prompt the KeyDescriptor if SP public certificate available

**Comment by timtrinidad** [comment]
The issue we observed was with Shibboleth (not sure which version); where encryption was enabled by default and the workflow failed when the SP no longer provided the encryption cert. The previous behavior allowed us to support clients who both encrypted or didn't encrypt, whereas after upgrading the workflow became more rigid.

I like what you said about modifying the getSPMetadata. I'll put in a PR for it.
