### ISSUE TITLE
Newb question

### ISSUE THREAD

**Issue by ohrickster** [onelogin/php-saml#332]
Why is the endpoints folder missing from the zip download of the master?

**Comment by pitbulk** [comment]
endpoints folder is just an example as well as demo1 or demo2. To reduce the number of files, I avoid downloading those and other files from zip / github export.

**Comment by ohrickster** [comment]
I guess I'm confused because the files are part of the "toolkit" and listed in the docs but there's no easy way to download the folder and it's files because they are excluded from the download?

**Comment by pitbulk** [comment]
demo1, demo2, endpoints.  All those folders contain demo/examples of use of the php-saml toolkit and are explained on the documentation.

You can git clone the repository in order to get all the files.
But demo2 and endpoints folders are excluded from export/zip.

The cause is that composer use similar method to collect the files from the repository than export/zip and I don't want to include them as a composer vendor dependence.
