### ISSUE TITLE
Call to undefined method OneLogin_Saml2_Settings::getValues()

### ISSUE THREAD

**Issue by misterjoonas** [onelogin/php-saml#38]
I'm trying to implement SLO for a Drupal module and I get the following error:
_Fatal error: Call to undefined method OneLogin_Saml2_Settings::getValues() in /var/www/builds/build_2014-08-04-075933/sites/all/libraries/php-saml/lib/Saml2/Settings.php on line 106_

This seems like an internal error of the toolkit, but most probably I'm doing something wrong in php.
All I'm trying to do is:
    $auth = new OneLogin_Saml2_Auth($samlSettings);
    $auth->processSLO();

The $samlSettings variable is generated in an internal function, and it works fine with the login process.

Here is the full error message, if it helps:
_Fatal error: Call to undefined method OneLogin_Saml2_Settings::getValues() in /var/www/builds/build_2014-08-04-075933/sites/all/libraries/php-saml/lib/Saml2/Settings.php on line 106 Call Stack: 0.0001 637176 1. {main}() /var/www/builds/build_2014-08-04-075933/index.php:0 0.3715 23239904 2. menu_execute_active_handler() /var/www/builds/build_2014-08-04-075933/index.php:21 0.3728 23267704 3. call_user_func_array() /var/www/builds/build_2014-08-04-075933/includes/menu.inc:517 0.3728 23267952 4. saml_sp__logout() /var/www/builds/build_2014-08-04-075933/includes/menu.inc:517 0.3773 23943512 5. OneLogin_Saml2_Auth->__construct() /var/www/drupal/code/modules/custom/saml_sp/saml_sp.pages.inc:82 0.3773 23944936 6. OneLogin_Saml2_Settings->__construct() /var/www/builds/build_2014-08-04-075933/sites/all/libraries/php-saml/lib/Saml2/Auth.php:59_

**Comment by shahidmau** [comment]
I'm getting the same error with yii2 framework.

**Comment by pitbulk** [comment]
Hi, I review this issue.

As you can analyze in the code, this happen when you try to [initialize the settings with an object](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Settings.php#L106).

The recommended ways to initialize the settings object are:
* Use the setting file
* Use an Array.

In order to maintain compatibility with the old version of the toolkit ([Saml library), we support
[OneLogin_Saml_Settings](https://github.com/onelogin/php-saml/blob/master/lib/Saml/Settings.php#L8) objects which has the [getValues](https://github.com/onelogin/php-saml/blob/master/lib/Saml/Settings.php#L57) method.

Resume: In order to initialize the auth or the  class OneLogin_Saml2_Settings you can provide nothing (the settings file will be read), an array or an OneLogin_Saml_Settings object, not a OneLogin_Saml2_Settings object.

**Comment by farooqv** [comment]
Hello @pitbulk 

I am using SAML with yii2, using yii2-saml .. I have sued the setting file but still getting same error? 

Service provider is my yii2 app, idp is okta sandbox. I connect that using simplesamlphph and that worked but seems problem in reading setting file.

in yii2-saml setting file name is saml.php.

**Comment by pitbulk** [comment]
Is a problem with yii2-saml implementation.
I reported the issue:
https://github.com/asasmoyo/yii2-saml/issues/2

**Comment by farooqv** [comment]
Thanks @pitbulk  , yea I just load direct setting files via onelogin php saml default setting file, it worked.
