### ISSUE TITLE
Please update packages on packagist.org: latest version are not available

### ISSUE THREAD

**Issue by laurentj** [onelogin/php-saml#381]
We cannot install latest version of packages (3.2.0, 3.2.1) from Composer, although these versions fix number of bugs. It seems that Packagist have not been updated with latest tags and branches of the repository.

Could you also explain why there is a branch for each tag in the repo? It's a bit tricky to checkout a branch instead of a tag, as branches and tags have the same name. And there is two tags in the repo v3.1.0 and 3.1.0. This is strange...

**Comment by pitbulk** [comment]
Forgot to sync it on packagist. Is done.

Related to the branch question.

Branches contain code not officially published. Once I consider something ready I create a github release and then a tag is available.
 
The 3.1.0 and the v3.1.0 were an experiment because a customer reported some issue when I started to publish the tags without the v so I created it with v to verify if that was really the issue or something not related.

**Comment by laurentj** [comment]
I confirm Packagist is updated, Thank you!
