### ISSUE TITLE
Open redirect - RelayState parameter?

### ISSUE THREAD

**Issue by porjo** [onelogin/php-saml#425]
Fortify static code analysis is complaining about `php-saml` v2.18.1 having an 'open redirect' in [Auth.php](https://github.com/onelogin/php-saml/blob/2.18.1/lib/Saml2/Auth.php#L336):
```php
 if (empty($url) && isset($_REQUEST['RelayState'])) {
            $url = $_REQUEST['RelayState'];
        }
```
It doesn't like the fact that it is defaulting to using the contents of `$_REQUEST`. Is that a safe assumption to make? If strict mode is enabled, and `$url` is empty, then perhaps it should fail instead?

**Comment by phosphore** [comment]
The [redirectTo](https://github.com/onelogin/php-saml/blob/master/docs/Saml2/classes/OneLogin_Saml2_Auth.html#L132) function redirects the user to the url passed by parameter or to the URL that we defined in our SSO Request.  The first condition for the redirect, `empty($url)`, is never satisfied since at the time of writing the function is always called with a non-empty `$url` in the code.

**Comment by pitbulk** [comment]
A warning will be raised if the $url parameter contains null, but the $url will be set to the $_REQUEST['RelayState'] if any.

I will document this fact on the description of the redirectTo method.

As @phosphore mentioned, in all the cases were redirectTo was used, the toolkit already registered a value for $url so that use case never happens.

@porjo Do you have any other concern?

**Comment by porjo** [comment]
Thanks, that sounds reasonable.
