### ISSUE TITLE
Destination attribute validation : impossible with ?args in the url

### ISSUE THREAD

**Issue by JohnDoe8521** [onelogin/php-saml#469]
Hi,

On the idp, Recipient url is : https://..../saml?acs

Because of "?acs" on this url and Utils::getSelfURLNoQuery() applied on currentUrl, the Destination Field can never be validated.

Could we have an option for : 
- have query on selfUrl, or
- get the Destination url attribute with the NoQuery Filter ?

Is there another solution ?

Thanks!

**Comment by pitbulk** [comment]
You can serve the ACS endpoint of the SP in any desirable URL, you have the control of the SP,
[demo1](https://github.com/onelogin/php-saml/tree/master/demo1) controls all endpoints using index.php and parameters, but [demo2](https://github.com/onelogin/php-saml/tree/master/demo2) has an specific file per endpoint.

That said, the ?acs should be taken propery by the toolkit, maybe you are using Apache/Nginx and not providing the right configuration in order to allow PHP retrieve vars like REQUEST_URI, QUERY_STRING,PATH_INFO .... used by the toolkit.
