### ISSUE TITLE
Using php-SAML with a Java Spring-boot 1.3.5 Application

### ISSUE THREAD

**Issue by Bioswami-nfac** [onelogin/php-saml#495]
Hello All, 

I have a peculiar situation. The Java Spring-boot version that we are using is an old one (v1.3.5). The JAVA SAML version we have seems to only work with later version. 

Here is what we are trying to do:

We have got the php SAML working. What we would ideally like to do is make a call to the phpSAML from our Java Application using a web service and get the response back from the php SAML.

Can you folks let us know how to do that?

Thanks in Advance.

Regards,
Arun

**Comment by pitbulk** [comment]
Gonna be the PHP code and the Java code in the same machine? otherwise, you will need to secure somehow the traffic between the 2 machines...

I believe that at the Java App, when you need to SSO, you will redirect the user to the PHP SSO Login page, it will generate an AuthNRequest to the IdP, then receive a SAMLResponse, at the SP ACS endpoint the SAMLResponse will be 
processed, if fails, an error should be shown, otherwise, you need to make the Java app aware that need to create a session for such user, one possible way is to enable at the Java server an endpoint protected by some OAuth/Oauth2, and the PHP app will be able to retrieve an access token and then, be able to communicate with the java Server in order to make it log the user... but if that is made in a back-channel,  how the session/cookie gonna be created in the user browser?
