### ISSUE TITLE
Auth#login(): rename `$returnTo` to `$relayState`

### ISSUE THREAD

**Issue by dakur** [onelogin/php-saml#496]
`Auth#login()` has [`$returnTo` parameter](https://github.com/onelogin/php-saml/blob/4.0.0/src/Saml2/Auth.php#L528) which is added to `RelayState` parameter of IdP endpoint.

But as far as I understand, it doesn't have to be URL at all, it's whatever you'd like to pass. [SAML docs](https://docs.oasis-open.org/security/saml/Post2.0/sstc-saml-tech-overview-2.0.html) (search for `RelayState` keyword) say it's a `token`, not a `resource`. [This SA thread](https://stackoverflow.com/a/34351756/3668474) explain it in short.

So I would say this `login()` parameter should be renamed as well to better reflect of what it is and how it can be used.

**Comment by pitbulk** [comment]
I'm aware that the RelayState is used to save the "State" and not just an "URL", but this SP implementation does not have a "State" and the way is implemented always consider the RelayState as an URL.

So at the login method, what you provide is an URL in order to redirect the user there once the SAMLResponse is processed on the ACS endpoint after calling processResponse.

**Comment by dakur** [comment]
Sorry, I use this lib completely out of onelogin's context, so I didn't know that. Thanks for response.
