### ISSUE TITLE
Security: Only support actively supported php versions

### ISSUE THREAD

**Issue by Hikariii** [onelogin/php-saml#59]
The readme and configuration is strong about php security in many ways but still allows end-of-life versions of PHP.
http://php.net/supported-versions.php
I suggest modifications to support php versions >= 5.4 since older releases do not get security support anymore.

**Comment by pitbulk** [comment]
Some of our customers use internal application that still uses PHP 5.3

We can recommend the use of updated PHP versions. Our toolkit works with PHP 5.3 so this is the minimum version that we required for use the toolkit. I will add a note in the README to notice that PHP 5.3 is unsupported.

P.S Notice that for example simpleSAMLphp has the same PHP version dependence:
https://simplesamlphp.org/docs/stable/simplesamlphp-install#section_3

**Comment by Hikariii** [comment]
I understand your point of view and still disagree. I very much support Anthony Ferrara's view (core php dev) on supporting older versions. http://blog.ircmaxell.com/2014/12/on-php-version-requirements.html.

Would you consider creating a up-to-date branch and releasing a new version of the library? This would also improve the usage of newer features in code. I think the codebase could benefit greatly from new php features like traits and many smaller enhancements.

**Comment by pitbulk** [comment]
Hi @Hikariii, I like the idea of creating a new branch that will require php5.6 / php6.
I can maintain both and keep improving the new SAML features. The unique requirement is to maintain the same settings name, and the main API functions.

We are already doing a similar thing in python in order to support python2.7 and python3.

Will you be available to help in this new branch? You can fork our project and start making some improvements, once stable, I can add all those changes for the proposed new branch.
