### ISSUE TITLE
missing fingerprint feature when processing the SLO

### ISSUE THREAD

**Issue by johansyd** [onelogin/php-saml#87]
see comment: https://github.com/onelogin/php-saml/commit/2e0ba98d98afb697d66e25f4420a2ac73c33015c#commitcomment-12905730

You should either update the README or add the missing feature.

**Comment by pitbulk** [comment]
When the signature of the IdP is embedded (HTTP-POST binding), then the "fingerprint trick" works, since I can validate the certificate associated with the signature using the fingerprint, and then use the whole certificate in order to validate the signature.

On HTTP-Redirect, the IdP certificate is not provide in the SAML Message so as you mention, the "fingerprint trick" does not work in this case.

I will update the README now.
